### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by PiSaucer** [Caligone/mc-icons#4]
each time I try to build it gives me this message:
```shell
Fatal error: Error while parsing JSON "TypeError: undefined is not a constructor (evaluating 'window.processCommand(params)')

  undefined:2
  :3
Images not loaded within 10 seconds. Timing out script.
".
Unexpected token T in JSON at position 0
```

Any ideas?

**Comment by Caligone** [comment]
The last time I worked on this project was 7 years ago.
If you want to work with this, you should probably rollback your NodeJS version around v0.8 (https://nodejs.org/en/download/releases/)

I will probably not work on it and should archive this repository
